### ISSUE TITLE
Create GHAction that will assign new issues to the Main Project Board

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1002]
- Need to set access token for this to work
  - the default, temporary `secrets.GITHUB_TOKEN` does not have sufficient access 
- Have team discussion before enabling

```
# This is a basic workflow to help you get started with Actions

name: Add New Issue to Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cdluc3/projects/5
          #github-token: ${{ secrets.GITHUB_TOKEN }}
```
