### ISSUE TITLE
Allow Merritt Docker Images to Reside in ECR or to exist locally (or in an artifact store)

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1020]
## Purpose
As we deploy integration test containers, we might want these to run on Jenkins, on a desktop, or in GitHub actions.

## Source Code
- Development Stack Images: https://github.com/CDLUC3/merritt-docker/tree/main/mrt-services
- Integration Test images: `mrt-it-services` instead of `mrt-services`

### Current ENV vars
Our docker environments expect the following vars to be set
```
export AWS_ACCOUNT_ID=`aws sts get-caller-identity| jq -r .Account`
export AWS_REGION=us-west-2
export ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
```

To allow this portability, we should consider renaming `ECR_REGISTRY` to `UC3_DOCKER_REGISTRY`.   (Avoiding naming this DOCKER_ in case of conflict).

### Compose File Conventions
Our compose file should then change from 
```
zoo:
    container_name: zoo
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-zookeeper:dev
    build:
      context: zoo
      dockerfile: Dockerfile
      args:
        ECR_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
```

To

```
  zoo:
    container_name: zoo
    image: ${UC3_DOCKER_REGISTRY}/mrt-zookeeper:dev
    build:
      context: zoo
      dockerfile: Dockerfile
      args:
        UC3_DOCKER_REGISTRY: ${UC3_DOCKER_REGISTRY}
```

## Proposed usage of UC3_DOCKER_REGISTRY variable
- Dev Servers: `${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com`
- Local images (in Jenkins or on desktop): `cdluc3-local-testing.cdlib.org`
  - Since `cdluc3` is a dockerhub user account, do not use this name unless you intend to publish for public use
- Using Artifact repo: TBD

## Maven Settings

Maven Property Default
```
<properties>
    <itDockerRegistry>cdluc3-local-testing.cdlib.org</itDockerRegistry>
  </properties>
```

Maven Property Setting based on ENV vars

Using current variables
```
<profiles>
       <profile>
           <id>aws</id>
           <activation>
               <property>
                   <name>env.AWS_ACCOUNT_ID</name>
               </property>
           </activation>
           <properties>
               <!-- Override only if necessary -->
               <itDockerRegistry>${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com</itDockerRegistry>
           </properties>
       </profile>
   </profiles>
```

Using Proposed Variables
```
  <profiles>
       <profile>
           <id>aws</id>
           <activation>
               <property>
                   <name>env.UC3_DOCKER_REGISTRY</name>
               </property>
           </activation>
           <properties>
               <!-- Override only if necessary -->
               <itDockerRegistry>${env.UC3_DOCKER_REGISTRY}</itDockerRegistry>
           </properties>
       </profile>
   </profiles>
```

Usage in Maven Plugin
```
<image>
  <name>${itDockerRegistry}/ezid_mock</name>
</image>
```

## Anticipated Integration Test Images
https://github.com/CDLUC3/merritt-docker/tree/main/mrt-inttest-services
