### ISSUE TITLE
[RELEASE] UC Berkeley ETD workflow change - 2022-06-08

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1082]
# Overview of Release
UCB LIT would like to switch their ETDs workflow such that ProQuest delivers ETD zips directly to CDL for processing.

# Service(s)
uc3-etds

# Github Issue Link(s)
https://github.com/CDLUC3/mrt-doc/issues/947

# Servers affected
uc3-etdx2

# Source Code:
Link(s) to tagged release(s)
https://github.com/CDLUC3/uc3-etds/pull/18

# Source Code Tag
28ab219438b15a935a7266adad1a0a22264d10a8
Note that an additional commit to the Production branch was made to provide a report to UCLA:
6a14e196bf1c2ea25498131382f6fb9040099366

# Deployment Steps (if applicable)
This deployment will involve three primary steps:
1. Deploy code changes, but roll back UCB campus config until ProQuest updates ETD Admin deliveries.
2. Once ETD Admin is updated, update config to settings in 28ab219438b15a935a7266adad1a0a22264d10a8
3. Comment out UCB-specific process to create eSchol links: line 973 in createmarc.py

- [x] Pull changes to Production box
- [x] Test ingest with two test ETDs: run getetds
- [x] Test marc record creation: run createmarc (no way to do so until an ETD is published in eSchol)
- [x] Remove ETDs from UCB ETD collection
- [x] Contact PQ and ask for ETD Admin change
Via new commit: 
- [x] Add DT to marc record notifications via new commit 
- [x] Comment out eSchol links procedure via a new commit

# Rollback Instructions
Move back to commit that precedes the above changes:
git checkout 8ed20edc28c104746efccf71c513f7d584dfa210

**Comment by elopatin-uc3** [comment]
Noting pre-deploy campus.yml config for Berkeley:

```
ucb:
    eschol: True
    eschol_abbr: ucb
    etd_delivery: False
    delivery_method: None
    create_marc: False
    delivery_marc: False
    delivery_csv: False
    pq_campus_code: 0028
    pqmarcxslt: None
    contact_email: None
    sftp_user: None
    sftp_retrieve_dir: None
    sftp_delivery_dir: None
```
