### ISSUE TITLE
Refactor Nagios alerts for Merritt microservices

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/mrt-doc#1317]
goals for mrt monitoring
------------------------
    
### Java Apps
    
- tomcat is responding
- targets in ALB TG are healthy
- secondary API calls are sane
    
```  
per service:
  access:
    ALB:
      hostname returns 200
        curl http://localhost:35121/hostname?t=xml
    nagios:
      hostname returns 200
      node state returns 200
        curl http://localhost:35121/state?t=xml
  audit:
    ALB: none
    nagios:
      state returns 200
        curl -s http://localhost:37001/mrtaudit/status?t=xml
      state contains 'running'
  ingest:
    ALB:
      state returns 200
        curl http://localhost:33121/state?t=xml
    nagios:
      state returns 200
      state contains 'thawed'
  inventory:
    ALB:
      state returns 200
        curl -v http://localhost:36121/mrtinv/state?t=xml
    nagios:
      state returns 200
      state contains 'running'
      db query is sane
        ??
  replic:
    ALB: none
    nagios:  
      state returns 200
        curl http://localhost:38001/mrtreplic/status?t=xml
      state contains 'running'
  store:
    ALB:
      hostname returns 200
        curl http://localhost:35121/hostname?t=xml
    nagios:
      hostname returns 200
      node state returns 200
        curl http://localhost:35121/state?t=xml
  sword:
    ALB: none
    nagios:
      servicedocument returns 200
        curl -X GET --user "xxx:zzzz" 'http://localhost:39001/mrtsword/servicedocument'
```

service escalations
-------------------

Groupings of merritt subservices
```
uc3-mrt-stg-svcs:
  desc: all dev/stg subservices
  escalations:
    1st hour:
    - CDL-uc3-mrt-email
    - CDL-ias-email-1
    2nd hour:
    - CDL-ias-email-2

uc3-mrt-prod-bkgr-svcs:
  desc: production background subservices
  escalations:
    1st hour:
    - CDL-uc3-mrt-email
    - CDL-ias-email-1
    2nd hour:
    - CDL-ias-email-2
  members:
  - uc3-mrt-audit-prd
  - uc3-mrt-batch-prd
  - uc3-mrt-build-prd
  - uc3-mrt-replic-prd
  - uc3-mrt-zookeeper-prd

uc3-mrt-prod-crit-svcs
  desc: production critical subservices
  escalations:
    1st hour:
    - CDL-uc3-mrt-email
    - CDL-ias-email-1
    2nd hour:
    - CDL-uc3-mrt-text
    - CDL-ias-email-2
    3rd hour:
    - CDL-ias-text-2
  members:
  - uc3-mrt-access-prd
  - uc3-mrt-etd-prd
  - uc3-mrt-ingest-prd
  - uc3-mrt-inventory-prd
  - uc3-mrt-store-prd
  - uc3-mrt-sword-prd
  - uc3-mrt-ui-prd
  - uc3-mrt-wasredirect-prd
  - uc3-mrt-ldap-prd
```

Contact Groups we use:
```
define contactgroup {
        contactgroup_name               CDL-uc3-mrt-email
        alias                           CDL-uc3-mrt-email
        members                         Mark Reyes,David Loy,Marisa Strong,Eric Lopatin,Terrence Brady,Ashley Gould,Slack Merritt
}

define contactgroup {
        contactgroup_name               CDL-uc3-mrt-text
        alias                           CDL-uc3-mrt-text
        members                         Mark Reyes Text,Mark Reyes,Marisa Strong Text,Marisa Strong,Terrence Brady,Terrence Brady Text,Ashley Gould Text
}

define contactgroup {
        contactgroup_name               CDL-ias-email-1
        alias                           CDL-ias-email-1
        members                         Joseph Somontan,Martin Haye,Slack IAS Alerts
}

define contactgroup {
        contactgroup_name               CDL-ias-email-2
        alias                           CDL-ias-email-2
        members                         Kurt Ewoldsen
}
