### ISSUE TITLE
Running FITS on prod batch server

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1712]
I am currently running FITS (https://projects.iq.harvard.edu/fits/get-started-using-fits) on the docker box out of an install in my home directory.

```
merritt: 
  credential: "{!SSM: objhealth/merritt_credential}"
  fits_command: "/home/tbrady/fits/fits.sh"
  fits_config: "/home/tbrady/fits/xml/fits_merritt.xml"
```

I am very eager to test this using some data that currently only exists in our PROD database.
The production version of the object health prototype runs on our PROD batch server from the dpr2 account.

The production version of the object health prototype runs on our PROD batch server from the dpr2 account.
Next week, I would like to do one of the following:
install FITS so dpr2 can run it from the PROD batch server
OR ask IAS to refresh our DEV database (from PROD) so that I can work with the newer objects that reside in prod
Ultimately, I may want to run FITS from a web service.  First we need to determine what it is able to reveal to us with some actual data in Merritt.

---

On 12/11, Joe discovered an issue with the mrt-sandbox host.  Running FITS triggered issues with /tmp disk on that box.

12/11, the Merritt team determined that we want to understand the footprint on this tool before running it in PROD.
