### ISSUE TITLE
Stage Collections for End to End Testing

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1856]
The Stage Guest Login has access to a bunch of empty DASH collections.

<img width="1354" alt="image" src="https://github.com/CDLUC3/mrt-doc/assets/1111057/ec324478-af73-4ad6-afa9-ffee36d1df1a">

For our end to end tests, we test that the Guest user can browse collections.

We need the following:
- At least 1 guest collection that is not empty
- At least 1 non-guest collection that is not empty

As we purge Dryad data, the test driver will break.

Here is what we current use in stage.

Please let me know a suitable replacement for cdl_dryaddev

```yml
  guest_actions:
    collections:
    - coll: cdl_dryaddev
    collections-no-access:
    - coll: ucla_digital_lib
  non_guest_actions:
    collections:
    - coll: merritt_demo
      submit: true
    - coll: cdl_wasabi
      submit: true
```
