### ISSUE TITLE
Create load test for stage

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#2016]
```
  test-files: 
    none:
      encoding-zip:
      ingest-files:
    load:
      encoding-zip:
      ingest-files:
      manifests:
      - coll: merritt_demo
        count: 10
        label: 'manufactured_load_A'
        url: 'https://merritt.cdlib.org/robots.txt'
        ext: '.txt'
      - coll: cdl_wasabi
        count: 10
        label: 'manufactured_load_B'
        url: 'https://merritt.cdlib.org/robots.txt'
        ext: '.txt'
      - coll: merritt_demo
        count: 100
        label: 'manufactured_load_C'
        url: 'https://merritt.cdlib.org/robots.txt'
        ext: '.txt'
      - coll: cdl_wasabi
        count: 10
        label: 'manufactured_load_D'
        url: 'https://merritt.cdlib.org/robots.txt'
        ext: '.txt'
      - coll: merritt_demo
        count: 100
        label: 'manufactured_load_E'
        url: 'https://merritt.cdlib.org/robots.txt'
        ext: '.txt'
```

![Image](https://github.com/user-attachments/assets/303ff669-717a-4534-8c09-093ee92e3985)

![Image](https://github.com/user-attachments/assets/aaaccf2f-61ba-497d-866b-1567b20683fa)
