### ISSUE TITLE
UCSB ETDs workflow changes

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#211]
### Summary
UCSB would like ProQuest to deliver their ETDs directly to CDL's SFTP server under the ProQuest (PQ) account there. This ticket encompasses all the tasks related to the requested workflow change.

### Tasks
- [x] Preliminary tests on ETDs Stage to determine `getetds.py` behavior when checking campus codes and scanning the `proquest` folder on the `sftp` server.
- [x] Update `campus.yml` with new PQ SFTP account entry for UCSB config
```
    sftp_user: ucsbetd <<< change to proquest
    sftp_retrieve_dir: ucsbetd <<< change to proquest
    sftp_delivery_dir: None
```
- [x] Scope and implement changes to `getetds.py` script
- [x] Update `app_config.yml` with PQ SFTP account entry for UCSB config (line 63)
```
sftpETDdirs:
    proquest: proquest
    ucla: uclaetd/etds
    ucsb: ucsbetd <<< change to proquest
```
